version: '3.8'

services:
  web:
    image: aljabernishad/basic-api:latest
    container_name: "api"
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8888:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: "db"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - .env

volumes:
  postgres_data:
