name: Build and Deploy Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: "aljabernishad/basic-api"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker Image
        run: docker build -t $DOCKER_IMAGE_NAME .

      - name: Run the Docker Image
        run: docker run -d -p 8000:8000 $DOCKER_IMAGE_NAME

      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKER_IMAGE_NAME
        
