name: Deploy to development environment
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: aljabernishad/basic-api-dev:${{ github.sha }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and push to dokcerhub
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker build -t $DOCKER_IMAGE_NAME .
          docker push $DOCKER_IMAGE_NAME

      - name: Copy the env file into machine
        run: |
          echo "${{ secrets.DEPLOYMENT_MACHINE_PASSWORD }}" | \
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
          -r .env.dev ${{ secrets.DEPLOYMENT_MACHINE_USERNAME }}@${{ secrets.DEPLOYMENT_MACHINE_HOST }}:~/

      - name: SSH into the deployment machine and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_MACHINE_HOST }}
          username: ${{ secrets.DEPLOYMENT_MACHINE_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_MACHINE_PASSWORD }}
          script: |
            docker pull $DOCKER_IMAGE_NAME
            docker run -d --name basic-api-dev -p 8000:8000 $DOCKER_IMAGE_NAME
